#!/bin/bash

deploy_container() {
	local domain=$1
	local app=$2
	local image=$3
	local port=$(find_free_port)
	local default=$4

	mkdir -p /tmp/docker/$domain/$app

	if [ $default ]; then
		echo -e "Deploying \e[1m$app.$domain\e[0m ($image) on port $port set to \e[1mdefault\e[0m"
		save_metadata $domain $app default true
	else
		echo -e "Deploying \e[1m$app.$domain\e[0m ($image) on port $port"
		save_metadata $domain $app default false
	fi

	echo $port > /tmp/docker/$domain/$app/port
	local app_id=$(docker run -d -p $port:80 --name app-$domain-$app-$port-$RANDOM $image)

	configure_nginx $domain $app $port $default
	save_metadata $domain $app id $app_id
	save_metadata $domain $app app $app
	save_metadata $domain $app image $image
	save_metadata $domain $app domain $domain

	echo "Finding old instances of $app.$domain to undeploy"
	for id in $(docker ps --no-trunc | grep -v :$port | grep app-${domain}-${app}- | awk '{print $1}'); do
		docker stop $id
	done
}

undeploy_container() {
	local domain=$1
	local app=$2

	if [ x$(has_app $domain $app) == xyes ]; then
		echo -e "\e[1mUndeploy $app.$domain\e[0m"
		docker stop $(cat /tmp/docker/$domain/$app/id)
		rm -f /etc/nginx/conf.d/${domain}-${app}.conf
		nginx -s reload
		rm -rf /tmp/docker/$domain/$app
	fi
}

has_app() {
	local domain=$1
	local chapp=$2

	for uid in $(docker ps --no-trunc -q); do
		local app=$(get_app_from_id_with_domain $domain $uid)
		if [ x$app == x$chapp ]; then
			echo yes
			return;
		fi
	done
}

get_app_from_id_with_domain() {
	local domain=$1
	local uid=$2

	grep -l $uid /tmp/docker/$domain/*/id | awk -F'/' '{print $5}'
}

get_domain_app_from_id() {
	local uid=$1

	local path=$(grep -l $uid /tmp/docker/*/*/id)
	path=${path%/id}

	echo $(cat $path/domain) $(cat $path/app)
}

configure_nginx() {
	local domain=$1
	local app=$2
	local port=$3
	local listen=$4
	
	if [ $listen ]; then
		listen="80 default";
	else
		listen=80;
	fi

	echo "
	server {
		listen $listen;
		server_name ${app}.$domain;
		location / {
			proxy_pass http://127.0.0.1:$port;
		}
	}
	" > /etc/nginx/conf.d/${domain}-${app}.conf
	nginx -s reload
}

save_metadata() {
	local domain=$1
	local app=$2
	local key=$3
	local value=$4

	mkdir -p /tmp/docker/$domain/$app
	echo $value > /tmp/docker/$domain/$app/$key
}

get_metadata() {
	local domain=$1
	local app=$2
	local key=$3

	cat /tmp/docker/$domain/$app/$key
}

find_free_port() {
	for port in $(seq 30000 39999); do
		if ! netstat -nta | grep -q $port; then
			echo $port;
			break;
		fi;
	done
}

setup_host() {
	check_release

	# Install Docker from the latest Docker repos
	apt-key adv \
		--keyserver hkp://keyserver.ubuntu.com:80 \
		--recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
	echo deb https://get.docker.com/ubuntu docker main > /etc/apt/sources.list.d/docker.list
	apt-get update
	apt-get install -y lxc-docker

	# Install nginx and configure nginx
	apt-get install -y nginx
	rm -f /etc/nginx/sites-available/* /etc/nginx/sites-enabled/*
}

check_release() {
	local version=$(lsb_release -rs)

	# Make sure this is a supported version
	case $version in
		14.04)
			echo "Detected Ubuntu $version LTS, supported!"
			;;
		*)
			echo "Detected $version, not supported."
			echo "Aborted!"
			exit 1
			;;
	esac
}

list_apps() {
	for uid in $(docker ps --no-trunc -q); do
		local domain_app=$(get_domain_app_from_id $uid)

		local domain=$(echo $domain_app | awk '{print $1}')
		local app=$(echo $domain_app | awk '{print $2}')
		local port=$(get_metadata $domain $app port)
		local image=$(get_metadata $domain $app image)
		local default=$(get_metadata $domain $app default)

		if [ $default ]; then
			echo "$app.$domain ($image):80 ⇄ $port [default]"
		else
			echo "$app.$domain ($image):80 ⇄ $port"
		fi

	done
}

case $1 in
	deploy)
		deploy_container $2 $3 $4 $5
		;;
	undeploy)
		undeploy_container $2 $3
		;;
	setup)
		setup_host
		;;
	list)
		list_apps
		;;
esac
